{% set name = "pyexplainer" %}
{% set version = "0.1.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f48facf6cd60d9ae576d266074dbf1743640c0a3cc06d1f577426a216b4a89f0

build:
  script: "{{ PYTHON }} -m pip install . -vv"
  number: 0
  noarch: python
  
requirements:
  host:
    - python >=3.8
    - pip
    - poetry
  run:
    - python >=3.8
    - scikit-learn
    - numpy
    - scipy
    - ipywidgets
    - ipython
    - pandas
    - statsmodels

test:
  imports:
    - pyexplainer   

about:
  home: https://github.com/awsm-research/pyExplainer
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'An Explainable AI tool for Software Analytics'
  description: |
    pyexplainer is a python package that generates explainable Machine Learning predictions
    from the so-called 'black-box model' such as random forest, moreover, pyexplainer 
    provides interactive visualisation that simplifies the decision-making process for
    Software Engineering.
  doc_url: https://pyexplainer.readthedocs.io/en/latest/?badge=latest
  dev_url: https://github.com/awsm-research/pyExplainer

extra:
  recipe-maintainers:
    - MichaelFu1998-create
