{% set name = "pyexplainer" %}
{% set version = "0.2.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8109cc9b67d42c33860a45e20216a510c074a91282817e895298f32081d7afb4


build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.8
    - pip
    - poetry
  run:
    - python >=3.8
    - scikit-learn
    - numpy
    - scipy
    - ipywidgets
    - ipython
    - pandas
    - statsmodels

test:
  imports:
    - pyexplainer

about:
  home: https://github.com/awsm-research/pyExplainer
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: An Explainable AI tool for Software Analytics
  description: |
    pyexplainer is a python package that generates explainable Machine Learning predictions
    from the so-called 'black-box model' such as random forest, moreover, pyexplainer 
    provides interactive visualisation that simplifies the decision-making process for
    Software Engineering.
  doc_url: https://pyexplainer.readthedocs.io/en/latest/?badge=latest
  dev_url: https://github.com/awsm-research/pyExplainer

extra:
  recipe-maintainers:
    - MichaelFu1998-create
